### ISSUE TITLE
Affichage des valeurs des indicateurs au sein de diagrammes

### ISSUE THREAD

**Issue by SylvainH-LSN** [La-Societe-Nouvelle/LaSocieteNouvelle-Website#11]
Affichage pour les indicateurs de type _contribution_ et _intensité_ d'un diagramme, resp. _secteur_ et _historigramme_, avec la valeur associée à l'unité légale et une valeur de référence.
L'objectif est de fournir une appréciation visuelle de la valeur par rapport à une référence (production intérieure française, production de la branche économique de l'unité légale, etc.).

**Comment by lyderic-dutillieux** [comment]
La valeur de référence est une moyenne ou un objectif ?
Dans le premier cas, il peut etre judicieux de mettre un objectif également ?

**Comment by SylvainH-LSN** [comment]
La valeur de référence correspond à la valeur de l'indicateur pour l'agrégat macro-économique le plus proche (Dans un premier temps, la production intérieure ou disponible française). L'objectif de cette valeur est d'avoir un élément de comparaison. L'affichage d'une valeur en tant qu'objectif est pour l'instant écarté. La Société Nouvelle n'est pas en position d'associer un objectif à chaque entreprise, qui doit prendre en compte la réalité de l'entreprise. Et l'affichage d'un objectif à l'échelle macro-économique (tel que sur les pages d'information des indicateurs) pourrait prêter à confusion.
